### ISSUE TITLE
Release / binaries

### ISSUE THREAD

**Issue by LixYt** [ookii-dialogs/ookii-dialogs-winforms#101]
Hello,

Can you please at a DLL package in addition of nuget into the releases ?
I think it would be great in case (as mine) where you need to call DLL's outside Visual studio (such as Streamer.Bot or any tool that has a C# embded compiler).

Best regards

**Comment by augustoproiete** [comment]
@LixYt This project targets multiple frameworks thus it generates multiple DLLs (and PDBs) (4 + 4 at the moment, probably 5 + 5 when .NET 8 is released later this year), so adding these extra 8 files in the release notes would make it quite confusing.

<img width="640" alt="image" src="https://github.com/ookii-dialogs/ookii-dialogs-winforms/assets/177608/b6894162-8483-4a3c-a0cc-f89558c626e2">

[A NuGet package is just a `zip` file](https://nuget.info/packages/Ookii.Dialogs.WinForms/4.0.0)... You can just download the NuGet package and extract the contents to a folder and grab the DLL you need based on the .NET version you're targeting.

<img width="1440" alt="image" src="https://github.com/ookii-dialogs/ookii-dialogs-winforms/assets/177608/dc7d93a7-90b6-456b-9c9a-a89c1d50ef0d">

**Comment by augustoproiete** [comment]
@LixYt Also, you can automate this process as part of the release, if you want.

Here's an example using [Cake](https://cakebuild.net/) that downloads a NuGet Package from nuget.org, extracts its contents and grab the files that are needed for the release.

https://github.com/augustoproiete/ExcelDnaPack-NuGet/blob/v1.5.1/build.cake
