### ISSUE TITLE
希望对.net 4.5支持（Want：The lowest version supports NET 4.5）

### ISSUE THREAD

**Issue by ping9719** [ookii-dialogs/ookii-dialogs-winforms#65]
我看到你是这样的描述的：（I saw your upgrade report）
#47  （.NET 4.6.1 EoL is April 2022 and Visual Studio 2022 no longer installs it by default.）

我们的用户使用win7系统非常多，所以我们需要对低版本net的一个支持（There are many users of Windows 7，So we need to support lower versions of NET）

辛苦作者，谢谢。（thank）

**Comment by augustoproiete** [comment]
Hey @ping9719 thanks for reaching out.

If you need support for .NET Framework 4.5, you'll need to use [Ookii.Dialogs.Wpf v4.0.0](https://www.nuget.org/packages/Ookii.Dialogs.Wpf/4.0.0) or [Ookii.Dialogs.WinForms v1.2.0](https://www.nuget.org/packages/Ookii.Dialogs.WinForms/1.2.0) which both support .NET Framework 4.5

**Comment by ping9719** [comment]
是的，我现在就是使用的 1.2.0（Yes, I'm using 1.2 now）
但是更想使用最想版本，哈哈哈~（But prefer to use the most wanted version, lol~~） (✪ω✪)
